#!/bin/bash
# Copies the code of this project to the production web server.
DEV_PATH="/home/herm/development/gugelhupf/lib"
LIB_PATH="/usr/lib/cgi-bin/lib/ruby/"
echo --------------------------------------------------------------------------
echo
echo Publishing the Ruby code to ${LIB_PATH}.
rsync -rvt ${DEV_PATH}/*.rb ${LIB_PATH}/
echo
echo --------------------------------------------------------------------------

