# encoding: utf-8

list = DATA.read.split(/\s*,\s*/)
File.open( File.join('..', 'lib', 'surnamelist.txt'), 'w') do |f|
  f.print( list.uniq.sort.join("\n") )
end


__END__
Achsen, Ackerman, Adam, Adams, Adelsbach, Affler, Alsheimer, Altringer, Andres, Annen, Arbegans, Arens, Arenz, Arnoldi, Audensirk,
Bach, Backendorf, Baldauf, Bappert, Barboza, Bardeaux, Bares, Barnett, Bartelmes, Barth, Barthelmes, Bartholomey, Bartzen, Barz, Barzen, Basten, Bastgen, Bauer, Bauernschmitz, Bauerschmitz, Bauler, Baumann, Bechold, Becker, Beckmann, Bender, Berg, Berger, Bernick, Berrens, Berscheid, Berweiler, Bettliner, Biesdorf, Biewer, Binz, Bischoff, Biwer, Blasius, Blasl, Blesius, Bogler, Bohr, Boker, Bollendorf, Bollig, Bömmels, Boos, Borens, Borne, Borscheid, Bortenschlager, Braegelmann, Bragelman, Brand, Braun, Breiling, Breit, Breitung, Breuer, Briesch, Brinkmann, Brixius, Brosius, Broy, Bund, Bungwitz, Burg,
Callan, Carbange, Carbangé, Cartus, Casel, Caspari, Christmann, Chrysam, Claas, Claeren, Clahsen, Clair, Clär, Clark, Clasen, Clemens, Clerren, Clifford, Collisy, Conder, Conrad, Consmann, Cordel, Cram, Crames, Cröschel,
Daffner, Dalpke, Daniel, Dany, Daubach, Daufenbach, Daum, Daus, Davis, Debald, Deitert, Denhart, Dennert, Denzer, Derdinger, Derenbach, Dewald, Diederich, Diendorf, Dietz, Dinndorf, Ditgen, Dixen, Dixius, Dollerschell, Donnerschell, Döpp, Döppers, Dörr, Dovey, Drockenmüller, Drossen, Druckenmüller, Dünker, Düren,
Eckert, Edinger, Edringer, Egner, Ehlen, Ehresmann, Ehrhard, Eickkoff, Eifel, Eiffel, Elsen, Emig, Emmerich, Endres, Endrey, Engel, Ensch, Erasmi, Ettscheid, Eurener,
Faas, Fandel, Farsch, Fas, Fass, Faßhauer, Fassian, Fei, Feilen, Feiler, Feiten, Feld, Felten, Feltes, Felzen, Ferber, Ferger, Fisch, Fischer, Flesch, Foerger, Fögen, Föhr, Fonzen, Förger, Forsmann, Fous, Foust, Frechen, Frey, Frick, Friderici, Friedrich, Fritzen, Fuchsen, Funk, Fürst,
Gäbges, Gallagher, Gassen, Gebert, Geiben, Geiler, Geisen, Geller, Genevaux, Geyer, Geyler, Giese, Gilbert, Gillen, Girst, Göbert, Godefroid, Gödert, Goerens, Göhlen, Goldbach, Gomberg, Gombert, Görens, Görgen, Graaf, Graff, Grans, Granz, Grell, Greten, Grethen, Greverath, Griesbach, Grosch, Grubel, Grundhofer, Grünen, Grychtol, Gummersbach, Gusenburger, Gutka,
Haag, Habichtsberg, Häger, Hahn, Hain, Halen, Haller, Hamann, Hamm, Hammes, Hampel, Hank, Hart, Hartenkeil, Hartmann, Hary, Hasselberg, Hau, Haubrich, Haw, Heck, Hegger, Heil, Heimfahrt, Hein, Heinen, Heintz, Heinz, Helbach, Helfen, Hellenbrant, Hengesberg, Henn, Hennen, Hennes, Henning, Hentges, Herber, Herbert, Herbertz, Herget, Hermann, Hermes, Hermesdorf, Herres, Herrig, Hettinger, Heying, Heynen, Hill, Hilsamer, Hockler, Hoff, Hoffman, Hoffmann, Höfling, Hohenbild, Holzemer, Holzschuh, Horch, Horsch, Hoste, Huben, Huerse, Hungershöfer, Huntzinger, Hurkes, Huschens, Hutmacher,
Illgen, Inderrieden, Irmisch, Israel,
Jacobi, Jacobs, Jacoby, Jäger, Jegen, Jochem, Jodoci, Joeres, Johann, Johäntges, Johnson, Johnston, Jonas, Jones, Josten, Jostock, Jostok, Jucken, Juncker, Jüncker, Jung, Jungelen, Jungen, Jüngling, Junk, Junkes, Justiger,
Kaap, Kackert, Kahn, Kalthoff, Kamp, Kanth, Kanzler, Kascht, Kayser, Kehren, Kellen, Kellersch, Keßler, Kesten, Keucker, Keuckert, Kiemen, Kimmlinger, Kirfel, Kirsch, Kistner, Klaes, Klas, Klein, Klemke, Kleutgen, Klotten, Klug, Knoop, Kohl, Kohn, Köhn, Köhnen, Kolb, Koley, Koll, Kollman, Kollmann, Kolz, Konder, Kopp, Kordel, Körperich, Koster, Kovar, Kraemer, Krämer, Kranz, Kratz, Krause, Krebs, Kreischen, Kremer, Krepp, Kreusch, Krieger, Kronenburg, Krones, Kröschel, Krumeier, Kruse, Kubitz, Kuhn, Kuhnen, Kurz,
Lachmich, Lafos, Lahr, Lamberti, Landgen, Landwein, Lanners, Laplage, Larusch, Laschet, Lauer, Laux, Laymann, Leders, Lehnen, Lehnert, Lehnertz, Leinen, Leisch, Leisen, Lellinger, Lentes, Lex, Leym, Licht, Lichter, Liebler, Lieser, Linden, Linn, Liser, Litsch, Löben, Loch, Loerwald, Longen, Lorang, Lörscher, Loskill, Loskyll, Lotz, Löwen, Ludes, Lutz, Lyser,
Maas, Mader, Madertz, Maes, Mai, Malambre, Malburg, Malone, Manderscheid, Mandler, Maringer, Marion, Marx, Marzi, Maßmann, Mathey, Mathieu, Mathy, Matthias, Mauer, Max, Maximini, May, Mayer, McCain, McLain, Mehling, Meilen, Meisberger, Meisterberg, Mentges, Mergen, Merges, Merten, Mertes, Mertesdorf, Merziger, Mesmer, Metzen, Metzler, Meurer, Meyer, Michels, Mies, Millard, Millen, Miller, Miranda, Mischo, Moersdorf, Möhn, Mohr, Mohrbach, Mohs, Molitor, Molz, Mommer, Montzel, Monzel, Morbach, Moseler, Mostert, Mülbers, Müller, Muthig,
Nagel, Naper, Nauert, Neesby, Neihs, Nenning, Neuen, Neuerburg, Neuf, Neukirch, Neumann, Neuses, Neyses, Niederweis, Nisius, Nistler, NN, Nosbisch, Nosbüsch, Nühnen, Nuyen,
Oberhauser, Oberkirch, Oligschläger, Olinger, Opgen-Rhein, Orth, Oster, Ostermaier, Ostermeyer, Ott, Otto,
Paga, Palmer, Palzer, Paul, Pauli, Pauly, Pax, Pelzer, Perrin, Petters, Pfeifer, Pfnör, Philippi, Philipps, Pick, Pitsch, Pitzen, Pletz, Plunien, Pooth, Poppelreiter, Porten, Preis, Preuß, Primer, Prinz, Probst, Prümm, Pusch, Pütz,
Quast, Quollert, Quant, Quint, Quasthof, Quitten, Quill,
Radermacher, Rammisch, Raub, Regneri, Reh, Reichert, Reifenberg, Reinert, Reis, Reiss, Reiß, Rengers, Rettweiler, Reuland, Reus, Reusrath, Reuter, Ring, Ripp, Rissler, Ritter, Röder, Roeder, Rohr, Rosenbaum, Rosenburg, Rosenkranz, Rößler, Roth, Royer, Rules, Rützel,
Sabel, Sackreuter, Sandrock, Sandrog, Sauer, Schaan, Schaar, Schädler, Schäfer, Scharkopf, Schauenburg, Schawe, Scheer, Schelbert, Scherr, Scherwas, Scheuer, Schienhoven, Schiff, Schilling, Schillings, Schilz, Schlader, Schleder, Schleichen, Schleider, Schleimer, Schlöder, Schloeder, Schmid, Schmidt, Schmit, Schmitt, Schmitz, Schmotz, Schneider, Schneiders, Schnitzius, Schoelen, Schoemann, Scholer, Scholl, Scholtes, Scholzen, Schömann, Schomer, Schömer, Schönhofen, Schons, Schopp, Schramel, Schramer, Schröder, Schroeder, Schroell, Schu, Schuh, Schuler, Schulgen, Schuller, Schüngel, Schuster, Schütz, Schweich, Schweicher, Schweißthal, Schwind, Schwinn, Sebastiani, Seher, Seier, Sensenschmidt, Sier, Sigri, Sikorski, Simon, Skupch, Slater, Sonntag, Sontag, Spaar, Spaeder, Spanier, Speicher, Spieles, Springer, Stanford, Steffen, Steffens, Steffes, Steffgen, Stein, Steinbach, Steinmetz, Stenger, Stieren, Stillwagen, Stoffel, Stoffels, Stolz, Streit, Stüber, Stumpf, Sturges, Stürmer, Succup,
Tallmann, Ternes, Teschenmacher, Tewinkel, Thanisch, Thanscheidt, Theis, Theissen, Thiel, Thielen, Thielgen, Thies, Thiesen, Tholl, Thomas, Thomaser, Thomé, Thomes, Thommet, Thormann, Thörnich, Thul, Thull, Tiegelkamp, Tilden, Tischler, Tömmel, Tömmes, Tonner, Torborg, Tornes, Törnich, Torres, Toßing, Treimetten, Trierweiler, Triesch, Trombetta, Tschumperlin, Tümmel,
Umbach, Ürtzig,
Valentini, Valerius, Veilleux, Velgart, Vesper, Viscardi, Volkemuth,
Wagener, Wagner, Wald, Walker, Wallenborn, Wallrath, Walter, Walters, Ward, Wassermann, Watz, Weber, Wegler, Weides, Weiland, Weiler, Weimer, Weinand, Weins, Weirich, Weis, Weismantel, Weiß, Weisz, Welsch, Welter, Wendel, Wener, Wengler, Werner, Werno, Weyer, White, Willems, Wingenfeld, Winter, Winterich, Wirschim, Wirth, Wirtz, Wirz, Witte, Wocken, Wolfers, Wollscheid, Würtz,
Xion, Xantor,
Yanish, Yezierski,
Zangerle, Zeigen, Zeitler, Zell, Zender, Zenz, Zeyen, Zimmer, Zimmermann, Zirbes, Zirpes, Ziwes, Zock, Zunker
