# encoding: UTF-8

# This generates a street name list from two input files:
# One with 'fixed' type street names, generated by gen_streetnames_fixed.rb
# and one with 'expandable' street names (those that can have different suffixes
# like 'street' or 'place'.
# 
# Format: One street per line, comments start with a hash sign.

name_suffix = %w(Straße Str. Gasse Weg Platz Allee Tal)
expandable_street_list_path = 'streetnames_expandable.txt'
# The following file is generated by gen_streetnames_fixed.rb:
fixed_street_list_path = 'streetnames_fixed.txt'
output_path = File.join( '..', 'lib', 'streetnamelist.txt' )

# Get the street names from the data in this file
street_names = []
File.open( expandable_street_list_path ) do |input|
  input.each do |base_name_as_read|
    base_name = base_name_as_read.force_encoding('UTF-8').chomp
    name_suffix.each do |suffix|
      full_name = case base_name[-1,1]
      when ('_')
        base_name[0..-2] + ' ' + suffix.capitalize
      when ('-')
        base_name + suffix.capitalize
      else
        base_name + suffix.downcase
      end
      street_names << full_name
    end  # End name_suffixes
  end  # End each (line / basename)
end  # End File

# Append the fixed street names to the Array street_names.
fixed_namelist = File.open( fixed_street_list_path, 'r' ) do |input|
  street_names.concat( input.readlines.collect { |l| l.chomp.force_encoding('UTF-8') } )
end

# Write the elements of the Array street_names to the output file.
File.open(output_path, 'w:utf-8') do |output|
  output.print street_names.sort.join("\n")
end
